services:
  indi:
    image: seanhoughton/rpi-indiserver:1.3.1 # rpi
    container_name: indiserver
    # command: indi_sbig_ccd indi_qhy_ccd indi_robo_focus indi_lx200gemini
    restart: always
    privileged: true
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/ttyUSB0:/dev/ttyUSB0
      - config:/root/.indi
    ports:
      - 7624:7624
    networks:
      indi-net:
        aliases:
          - indiserver
  web:
    image: indiweb:latest
    container_name: indiweb
    command: -x /root/.indi
    restart: always
    volumes:
      - config:/root/.indi
    ports:
      - 8624:8624
    networks:
      indi-net:
        aliases:
          - indiweb

networks:
  indi-net:
    name: indi-net

volumes:
  config:
