# https://github.com/knro/indiwebmanager

FROM ubuntu

RUN apt-get update && apt-get install -y python3 pip

RUN pip install indiweb --break-system-packages

EXPOSE 8624
ENTRYPOINT ["/usr/local/bin/indi-web", "-v"]
