services:
  indi:
    image: indiserver:latest
    container_name: indiserver
    command: indi_synscanlegacy_telescope indi_asi_ccd indi_nikon_ccd
    restart: always
    privileged: true
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/ttyUSB0:/dev/ttyUSB0
      - config:/root/.indi
    ports:
      - 7624:7624
    networks:
      indi-net:
        aliases:
          - indiserver
  web:
    image: indiweb:latest
    container_name: indiweb
    command: -x /root/.indi
    restart: always
    volumes:
      - config:/root/.indi
    ports:
      - 8624:8624
    networks:
      indi-net:
        aliases:
          - indiweb

networks:
  indi-net:
    name: indi-net

volumes:
  config:
